const cities = [
  { name: "Leticia", department: "Amazonas", country: "Colombia" },
  { name: "Medellín", department: "Antioquia", country: "Colombia" },
  { name: "Arauca", department: "Arauca", country: "Colombia" },
  { name: "Barranquilla", department: "Atlántico", country: "Colombia" },
  { name: "Cartagena de Indias", department: "Bolívar", country: "Colombia" },
  { name: "Tunja", department: "Boyacá", country: "Colombia" },
  { name: "Manizales", department: "Caldas", country: "Colombia" },
  { name: "Florencia", department: "Caquetá", country: "Colombia" },
  { name: "Yopal", department: "Casanare", country: "Colombia" },
  { name: "Popayán", department: "Cauca", country: "Colombia" },
  { name: "Valledupar", department: "Cesar", country: "Colombia" },
  { name: "Quibdó", department: "Chocó", country: "Colombia" },
  { name: "Montería", department: "Córdoba", country: "Colombia" },
  { name: "Bogotá", department: "Cundinamarca", country: "Colombia" },
  { name: "Puerto Inírida", department: "Guainía", country: "Colombia" },
  {
    name: "San José del Guaviare",
    department: "Guaviare",
    country: "Colombia",
  },
  { name: "Neiva", department: "Huila", country: "Colombia" },
  { name: "Riohacha", department: "La Guajira", country: "Colombia" },
  { name: "Santa Marta", department: "Magdalena", country: "Colombia" },
  { name: "Villavicencio", department: "Meta", country: "Colombia" },
  { name: "Pasto", department: "Nariño", country: "Colombia" },
  { name: "Cúcuta", department: "Norte de Santander", country: "Colombia" },
  { name: "Mocoa", department: "Putumayo", country: "Colombia" },
  { name: "Armenia", department: "Quindío", country: "Colombia" },
  { name: "Pereira", department: "Risaralda", country: "Colombia" },
  {
    name: "San Andrés",
    department: "San Andrés y Providencia",
    country: "Colombia",
  },
  { name: "Bucaramanga", department: "Santander", country: "Colombia" },
  { name: "Sincelejo", department: "Sucre", country: "Colombia" },
  { name: "Ibagué", department: "Tolima", country: "Colombia" },
  { name: "Cali", department: "Valle del Cauca", country: "Colombia" },
  { name: "Mitú", department: "Vaupés", country: "Colombia" },
  { name: "Puerto Carreño", department: "Vichada", country: "Colombia" },
];

export default cities;
