import {
    Hotel,
    HotelEmail,
    HotelLocation,
    HotelPassword,
    HotelName,
    HotelPlan,
    HotelRole,
    HotelScore,
    HotelStatus,
    ProviderData,
    CreatedAt,  
    HotelRepository
    
} from "../../domain";

const VALID_PLAN = ['FREE', 'BASIC', 'PREMIUM'] as const;
const VALID_STATUS = ['OPEN', 'CLOSED', 'BLOCKED'] as const;
const VALID_ROLE = [ 'HOTEL', 'HOTELADMIN'] as const;
const VALID_PROVIDER_DATA = ['AUTH', 'AUTHGOOGLE', 'AUTHFACEBOOK'] as const;
const DEFAULT_SCORE = 0 // valor por defecto;


export interface HotelCreateHandlerProps {
    name: HotelName;
    email: HotelEmail;
    password?: HotelPassword;
    location: HotelLocation;
    plan: HotelPlan;
    status: HotelStatus;
    role: HotelRole;
    score?: HotelScore;
    providerData: ProviderData;
    createdAt: CreatedAt;
    
}

interface HotelResponses {
    data: ReturnType<Hotel["toResponse"]>;
}

export class HotelCreate{

    constructor(private readonly repository: HotelRepository){}

    //validar que los objetos no sean nulos o undefined

    async handler(props: HotelCreateHandlerProps): Promise<HotelResponses> {
         if (!props.plan || !props.status || !props.role || !props.score || !props.providerData || !props.createdAt || !props.updatedAt){    
        throw new Error("Todos los campos son requeridos");

    }
    //no null o undefined
    const planValue = props.plan.getValue();
    if (planValue === undefined || planValue === null) {
        throw new Error("El plan es requerido");
    }

    const statusValue = props.status.getValue();
    if (statusValue === undefined || statusValue === null) {
        throw new Error("El status es requerido");    }

    const roleValue = props.role.getValue();
    if (roleValue === undefined || roleValue === null) {
        throw new Error("El role es requerido");
    }   

    const ProviderDataValue = props.providerData.getValue();
    if (ProviderDataValue === undefined || ProviderDataValue === null) {
        throw new Error("El providerData es requerido");
    }
    
    
    // validar enums con switch en los value objects
    switch (planValue) {
        case 'FREE':
        case 'BASIC':
        case 'PREMIUM':
            break;
        default:
            throw new Error(`Invalid plan ${planValue} must be one of ${VALID_PLAN.join(', ')}`);
    }


    switch (statusValue) {
        case 'OPEN':
        case 'CLOSED':
        case 'BLOCKED':
            break;
        default:
            throw new Error(`Invalid status ${statusValue} must be one of ${VALID_STATUS.join(', ')}`);
    }

    switch (roleValue) {
        case 'HOTEL':
        case 'STAFF':
            break;
        default:
            throw new Error(`Invalid role ${roleValue} must be one of ${VALID_ROLE.join(', ')}`);
    }

    switch (ProviderDataValue) {
        case 'AUTH':
        case 'AUTHGOOGLE':
        case 'AUTHFACEBOOK':
            break;
        default:
            throw new Error(`Invalid providerData ${ProviderDataValue} must be one of ${VALID_PROVIDER_DATA.join(', ')}`);
        
    }
    // validar otros campos requeridos

    if (!props.name || !props.email || !props.location) {
        throw new Error("name, email and location are required");
    }

    //asignar valores por defecto

    const score = props.score ?? DEFAULT_SCORE
    const createdAt = props.createdAt ?? CreatedAt.now();
    



    // Crear el objeto Hotel sin HotelId (sera genrado por la base de datos)
    const hotel = new Hotel({
        name: props.name,
        email: props.email,        
        location: props.location,
        plan: props.plan,
        role: props.role,
        score: score,
        status: props.status,
        createdAt: createdAt,        
        providerData: props.providerData,
    });

    const createdHotel = await this.repository.create(hotel) as Hotel;
    

    //Asegurar que el hotel retornado tiene un HotelId generado por la base de datos MongoDB
    if (!createdHotel.hotelId) {
        throw new Error("Hotel creation failed: No HotelId generated by repository");
    }

    //devolver respuesta

    return {data: createdHotel.toResponse()};
        
    }
   
    
} 
