export * from "./Hotel-created-at";
export * from "./HotelEmail";
export * from "./HotelId";
export * from "./HotelLocation";
export * from "./HotelName";
export * from "./HotelPassword";
export * from "./HotelPlan";
export * from "./HotelStatus";
export * from "./Hotel-updated-at";
export * from "./ProviderData";
export * from "./HotelRole";
export * from "./HotelScore";
export * from "./HotelPicture"
export * from "./HotelFreePlanEnd"